### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by Scr3amer** [Scr3amer/DummyRepoToTalkToPeople#1]
@mstorsjo

Hey :) !

Just wanted to ping you cause I was listening a podcast with the guy who managed VLC project and he mentionned the name of a dev who coded in ASM Neon on his phone. A certain Mr Storsjo.

It made me smile knowing how small the programming world was.

Check at 22:30:
https://shows.acast.com/micode-underscore/episodes/la-face-cachee-du-port-hdmi

Podcast was about patents and mafia of the codec industry.

**Comment by mstorsjo** [comment]
> Just wanted to ping you cause I was listening a podcast with the guy who managed VLC project and he mentionned the name of a dev who coded in ASM Neon on his phone. A certain Mr Storsjo.
> 
> It made me smile knowing how small the programming world was.
> 
> Check at 22:30: https://shows.acast.com/micode-underscore/episodes/la-face-cachee-du-port-hdmi
> 
> Podcast was about patents and mafia of the codec industry.

Thanks, it's indeed a small world!

I tried listening to that podcast, but I don't really find any mention within that podcast episode - I tried listening around at 22:30 (and at other spots) but didn't quite find anything like it. (I don't speak french but I try to at least follow what's being spoken about...)

**Comment by Scr3amer** [comment]
@mstorsjo

Oh sorry I linked the wrong podcast.

That's the one about codecs.  Go to 22:40 for the mention.
The other one was about HDMI / HDCP and such...


https://shows.acast.com/micode-underscore/episodes/apple-vs-google-la-video-pour-champ-de-bataille

**Comment by mstorsjo** [comment]
> @mstorsjo
> 
> Oh sorry I linked the wrong podcast.
> 
> That's the one about codecs. Go to 22:40 for the mention. The other one was about HDMI / HDCP and such...
> 
> https://shows.acast.com/micode-underscore/episodes/apple-vs-google-la-video-pour-champ-de-bataille

Thanks! That was nice to hear!
